apiVersion: v1
kind: Service
metadata:
  name: jaeger-public
spec:
  type: LoadBalancer
  ports:
  - port: 16686
    targetPort: 16686
    protocol: TCP
  selector:
    app: jaeger-app
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
  - port: 6831
    targetPort: 6831
    protocol: UDP
  selector:
    app: jaeger-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jaeger-app
    spec:
      containers:
      - name: jaeger-pod
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
        - containerPort: 6831
          protocol: UDP       