spring:
  application:
    name: camunda-retry-service
  jpa: 
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://mysql:3306/camunda?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
camunda:
  bpm:
    database:
      type: mysql
#  main:
#    allow-bean-definition-overriding:true
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.dchavez: DEBUG
server:
  port: 8081
product-service: http://product-service:8082/products/
opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
   
